### ISSUE TITLE
Contacto

### ISSUE THREAD

**Issue by yorhg** [PieroMateo/Juego-de-trivia#6]
Hola, soy tu compañero de la clase de Silabuz, me pasas tu contacto para el entregable de esta semana?

**Comment by PieroMateo** [comment]
si te refieres a mi link de mi programa en github, aqui te lo dejo
https://github.com/PieroMateo/Juego-de-trivia/issues , creo que hay que
llenar un formulario con esos datos, pasame el tuyo tambien porfa.

**Comment by yorhg** [comment]
https://github.com/yorhg/Trivia_Silabuz
Agregame nuevamente el issue o agrega otro pls, tuve que cambiar el repositorio.
Escribeme al whatsapp para estar en contacto 982375888

**Comment by PieroMateo** [comment]
normal, yo le agrego un issue nuevo, yo creo que tambien cambiare mi
codigo, apenas termino te aviso ps

**Comment by PieroMateo** [comment]
contacto como amigo, a que te refieres exactamente?
